"""Dark-by-default passive broker contracts; contains no network adapter."""

# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 ChaseInTech

from greytheory_broker.contracts import (
    POLICY_VERSION,
    RECEIPT_SCHEMA_VERSION,
    TICKET_SCHEMA_VERSION,
    BrokerContractError,
    BrokerLimits,
    PassiveMethod,
    PassiveReceiptPayload,
    PassiveTicketIssuer,
    PassiveTicketPayload,
    ReceiptOutcome,
    SignedPassiveReceipt,
    SignedPassiveTicket,
)
from greytheory_broker.guard import (
    BrokerDenied,
    BrokerDenialReason,
    PassiveBrokerSession,
)
from greytheory_broker.encryption import (
    CAPTURE_ALGORITHM,
    CAPTURE_SCHEMA_VERSION,
    CaptureEncryptionError,
    CaptureRecipient,
    EncryptedCapture,
    decrypt_capture,
    encrypt_capture,
)
from greytheory_broker.keys import (
    KEY_STORE_SCHEMA,
    KEY_WRAP_ALGORITHM,
    CaptureKeyError,
    CaptureKeyRecord,
    CaptureKeyStatus,
    CaptureKeyStore,
)
from greytheory_broker.os_secrets import (
    ROOT_KEK_BYTES,
    ROOT_KEK_RECORD_MAX_BYTES,
    ROOT_KEK_RECORD_SCHEMA,
    WINDOWS_DPAPI_DESCRIPTION,
    WINDOWS_DPAPI_PROVIDER_ID,
    WINDOWS_DPAPI_SCOPE,
    RootKekLease,
    RootKekProviderError,
    WindowsDpapiBackend,
    WindowsDpapiRootKekProvider,
    open_capture_key_store,
)
from greytheory_broker.storage import (
    BrokerKillSwitch,
    BrokerStorageError,
    KillSwitchState,
    RateLimitDenied,
    TicketReplayDenied,
    TicketReplayLedger,
    TicketReservation,
)
from greytheory_broker.signing import (
    ED25519_ALGORITHM,
    Ed25519Signer,
    Ed25519Verifier,
    MessageSigner,
    MessageVerifier,
    SigningError,
)
from greytheory_broker.url_policy import (
    TargetPolicyError,
    canonical_hostname,
    canonical_https_url,
    public_addresses,
)

__all__ = [
    "POLICY_VERSION",
    "RECEIPT_SCHEMA_VERSION",
    "TICKET_SCHEMA_VERSION",
    "BrokerContractError",
    "BrokerDenied",
    "BrokerDenialReason",
    "BrokerKillSwitch",
    "BrokerLimits",
    "BrokerStorageError",
    "CAPTURE_ALGORITHM",
    "CAPTURE_SCHEMA_VERSION",
    "CaptureEncryptionError",
    "CaptureKeyError",
    "CaptureKeyRecord",
    "CaptureKeyStatus",
    "CaptureKeyStore",
    "CaptureRecipient",
    "ED25519_ALGORITHM",
    "Ed25519Signer",
    "Ed25519Verifier",
    "EncryptedCapture",
    "KEY_STORE_SCHEMA",
    "KEY_WRAP_ALGORITHM",
    "KillSwitchState",
    "MessageSigner",
    "MessageVerifier",
    "RateLimitDenied",
    "PassiveBrokerSession",
    "PassiveMethod",
    "PassiveReceiptPayload",
    "PassiveTicketIssuer",
    "PassiveTicketPayload",
    "ReceiptOutcome",
    "ROOT_KEK_BYTES",
    "ROOT_KEK_RECORD_MAX_BYTES",
    "ROOT_KEK_RECORD_SCHEMA",
    "RootKekLease",
    "RootKekProviderError",
    "SignedPassiveReceipt",
    "SignedPassiveTicket",
    "SigningError",
    "TargetPolicyError",
    "TicketReplayDenied",
    "TicketReplayLedger",
    "TicketReservation",
    "WINDOWS_DPAPI_DESCRIPTION",
    "WINDOWS_DPAPI_PROVIDER_ID",
    "WINDOWS_DPAPI_SCOPE",
    "WindowsDpapiBackend",
    "WindowsDpapiRootKekProvider",
    "canonical_hostname",
    "canonical_https_url",
    "decrypt_capture",
    "encrypt_capture",
    "open_capture_key_store",
    "public_addresses",
]
